### ISSUE TITLE
Chatbot support?

### ISSUE THREAD

**Issue by mwarkentin** [aws-samples/aws-health-organizational-view-alerts#2]
I'm curious if AWS Chatbot supports AWS Health Organization Events in any way? Might be nice if we could manage the Slack integration and message formatting using that?

I suppose we would still need something like this solution to check if the health events have been updated? 

https://docs.aws.amazon.com/chatbot/latest/adminguide/related-services.html

**Comment by jordanaroth** [comment]
Currently, no chatbot works off of CloudWatch Events and Service Health Dashboard (SHD) events go through the Health API, not CloudWatch. Asked that it be added to the roadmap.
