### ISSUE TITLE
Add filters to reduce noise

### ISSUE THREAD

**Issue by feichashao** [aws-samples/aws-health-organizational-view-alerts#4]
We want to set up slack alerts to let SRE knows there's a LSE on AWS side, so we can take care of the aws resources accordingly.

After setting up the alert on slack, we found that there are many alerts flooding the slack channel. Many of those alerts are "notification" level which does not have actual impact to the environment.  Having too many "no-ops" alerts might lead to nobody care about the alert channel, which make it useless.

To reduce noise, we can add a paginator filter, for example, 'eventTypeCategories'=['issue'].

Ref:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/health.html#Health.Paginator.DescribeEventsForOrganization.paginate

https://docs.aws.amazon.com/health/latest/APIReference/API_DescribeEventsForOrganization.html

https://docs.aws.amazon.com/health/latest/APIReference/API_OrganizationEventFilter.html

**Comment by jordanaroth** [comment]
@feichashao apologies for the lateness of the reply. My co-author and I have been working on a brand new solutions that incorporates exactly what you are looking for in a solution we call AWS Health Aware. We just made it public and you can view it here: https://github.com/aws-samples/aws-health-aware
